input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if ![serviceName] {
    mutate {
      add_field => { "serviceName" => "healthsys" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "healthsys-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
