apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-record-service
  template:
    metadata:
      labels:
        app: medical-record-service
    spec:
      containers:
        - name: medical-record-service
          image: healthsys/medical-record-service:latest
          env:
            - name: SPRING_APPLICATION_NAME
              value: healthsys-medical-record-service
            - name: HEALTHSYS_SERVICE_ROLE
              value: medical-record
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medical-record-service
spec:
  selector:
    app: medical-record-service
  ports:
    - port: 8080
      targetPort: 8080
